spring.application.name: gateway
server.port: 8080

eureka.client.region: default
eureka.client.registryFetchIntervalSeconds: 5

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  prefix: /api